### ISSUE TITLE
Feature request: remove "Last viewed: " prefix in project explorer

### ISSUE THREAD

**Issue by BenceSzalai** [yaohui-wyh/StatisticsView#1]
Hi! It is a great plugin, nice addition to my workflow. Not only for statistics, but sometimes I look at menu files wondering which one was that I looked at 2 minutes ago. It helps being more productive.

With one little caveat: the "Last viewed: " prefix in front of the important information forces me to make the project explorer toolbar wider, which takes valuable screen space.

Imho whoever installed the plugin would know exactly what "5 minutes ago (5 times, total 50 s)" means. Showing "Last viewed: " in each line is redundant.

Please add an option, to disable this prefix text!

Thank you!

**Comment by yaohui-wyh** [comment]
Hi @BenceSzalai You can specify the statistics hint text using a template (via adding a line to VM Options & restart IDE), e.g. `-DstatisticsView.hint.template={lv}. ({oc} times, total {tm})`. PTAL at PR #2 for details.

**Comment by BenceSzalai** [comment]
Great, thanks you! I've went straight away to set it up, but realised I need to wait for the next release! :)

EDIT: Ok, I can see now the manual artefact download option. Will try soon!

**Comment by BenceSzalai** [comment]
Just tried. Works perfectly, thank you! Hope it'll be released in official plugin library as well.
